export const SET_PAGE_STEP = "SET_PAGE_STEP";
export const SET_INPUT_CHOICE = "SET_INPUT_CHOICE";
export const SET_FILE = "SET_FILE";
export const SET_TEXT_CONTENT = "SET_TEXT_CONTENT";
export const SET_NOTIFICATION_DETAILS = "SET_NOTIFICATION_DETAILS";
export const SET_ANALYSIS_RESULTS = "SET_ANALYSIS_RESULTS";
export const SET_NEW_CONTENT_STATE = "SET_NEW_CONTENT_STATE";
export const SET_ACTIVE = "SET_ACTIVE";
